import { useState, useEffect } from 'react';
import { FileText, ShieldAlert, CheckCircle, RefreshCw, Hash, ArrowRight } from 'lucide-react';
import { fetchWithConfig } from '../api';

function CleanupPlanPage() {
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(true);

  const loadPlan = async () => {
    setLoading(true);
    try {
      const data = await fetchWithConfig('/plans/latest');
      setPlan(data);
    } catch (err) {
      console.error("Failed to load plan:", err);
    }
    setLoading(false);
  };

  useEffect(() => {
    loadPlan();
  }, []);

  return (
    <div className="fade-in pb-12">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <h1 style={{ margin: 0 }}>Active Cleanup Plan</h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: 13, marginTop: 4 }}>
            Cryptographically sealed teardown plan generated by CloudScope
          </p>
        </div>
        <button onClick={loadPlan} className="btn btn-sm">
          <RefreshCw size={14} className="mr-1" /> Refresh
        </button>
      </div>

      {!plan ? (
        <div className="glass-panel" style={{ textAlign: 'center', padding: 60, color: '#a0a4a8' }}>
          <FileText size={40} color="#6c5ce7" style={{ margin: '0 auto 12px' }} />
          <div style={{ fontWeight: 700, color: '#fff' }}>No Active Cleanup Plan Generated</div>
          <div style={{ fontSize: 12, marginTop: 4 }}>Go to the Agent Console and run a scan to generate a plan.</div>
        </div>
      ) : (
        <div>
          {/* PLAN METADATA CARD */}
          <div className="glass-panel" style={{ marginBottom: 24, padding: 24 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 16 }}>
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <h2 style={{ margin: 0 }}>Plan v{plan.plan_version}</h2>
                  <span style={{
                    background: plan.status === 'PENDING_APPROVAL' ? '#f39c1225' : '#2ed57325',
                    color: plan.status === 'PENDING_APPROVAL' ? '#f39c12' : '#2ed573',
                    fontSize: 11, fontWeight: 700, padding: '3px 10px', borderRadius: 12
                  }}>
                    {plan.status}
                  </span>
                </div>
                <div style={{ fontSize: 12, color: '#a0a4a8', marginTop: 4 }}>
                  AWS Account: <strong style={{ color: '#fff' }}>{plan.aws_account_id}</strong> • Region: <strong style={{ color: '#fff' }}>{plan.region}</strong>
                </div>
                {plan.status === 'PENDING_APPROVAL' && (
                  <div style={{ marginTop: 10 }}>
                    <a href="/approvals" className="btn btn-primary btn-sm" style={{ textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                      <ShieldAlert size={14} /> Review & Auto-Terminate Candidates →
                    </a>
                  </div>
                )}
              </div>

              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: 20, fontWeight: 800, color: '#2ed573' }}>
                  ${plan.total_monthly_savings.toFixed(2)}/mo
                </div>
                <div style={{ fontSize: 12, color: '#a0a4a8' }}>
                  ${plan.total_annual_savings.toFixed(2)}/yr total potential savings
                </div>
              </div>
            </div>

            {/* Cryptographic Plan Hash */}
            <div style={{
              marginTop: 18, padding: '10px 14px', background: 'rgba(0,0,0,0.3)',
              borderRadius: 8, border: '1px solid rgba(255,255,255,0.08)',
              display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap'
            }}>
              <Hash size={16} color="#6c5ce7" />
              <span style={{ fontSize: 11, color: '#a0a4a8' }}>Plan Hash (SHA-256):</span>
              <code style={{ fontSize: 11, color: '#a29bfe', wordBreak: 'break-all' }}>{plan.plan_hash}</code>
            </div>

            <div style={{ marginTop: 12, fontSize: 12, color: '#888' }}>
              ℹ If infrastructure changes or candidates are modified, this hash updates automatically and invalidates previously approved actions.
            </div>
          </div>

          {/* CANDIDATES TABLE */}
          <div className="glass-panel" style={{ padding: 0, overflow: 'hidden' }}>
            <div style={{ padding: '16px 20px', borderBottom: '1px solid #ffffff10' }}>
              <h3 style={{ margin: 0, fontSize: 15 }}>Proposed Destructive Actions ({plan.candidates.length})</h3>
            </div>

            <div className="table-container">
              <table>
                <thead>
                  <tr>
                    <th>Resource</th>
                    <th>Type</th>
                    <th>Proposed Action</th>
                    <th>Monthly Savings</th>
                    <th>Finding & Evidence</th>
                    <th>Approval Status</th>
                  </tr>
                </thead>
                <tbody>
                  {plan.candidates.map(c => (
                    <tr key={c.resource_id}>
                      <td>
                        <div style={{ fontWeight: 700, color: '#fff' }}>{c.name}</div>
                        <div style={{ fontFamily: 'monospace', fontSize: 11, color: '#a0a4a8' }}>{c.resource_id}</div>
                      </td>
                      <td><code>{c.resource_type.toUpperCase()}</code></td>
                      <td>
                        <span style={{ color: '#ff4757', fontWeight: 700, textTransform: 'uppercase' }}>
                          {c.recommended_action}
                        </span>
                      </td>
                      <td style={{ color: '#2ed573', fontWeight: 700 }}>
                        ${c.monthly_cost.toFixed(2)}/mo
                      </td>
                      <td style={{ fontSize: 12, maxWidth: 300 }}>
                        <div style={{ color: '#f39c12', fontWeight: 600 }}>{c.waste_finding}</div>
                        <div style={{ color: '#a0a4a8', fontSize: 11, marginTop: 2 }}>
                          {c.evidence && c.evidence[0]}
                        </div>
                      </td>
                      <td>
                        <span style={{
                          background: c.requires_approval ? '#f39c1220' : '#2ed57320',
                          color: c.requires_approval ? '#f39c12' : '#2ed573',
                          padding: '3px 8px', borderRadius: 4, fontSize: 11, fontWeight: 700
                        }}>
                          {c.requires_approval ? 'Required' : 'Safe'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default CleanupPlanPage;
